export const errorCode = {
  invalid: "Error_Invalid",
  unthenticated: "Error_Unthenticated",
  attack: "Error_Attack",
  accessTokenExpired: "Error_AccessTokenExpired",
  userExist: "Error_UserAlreadyExisted",
  overLimit: "Error_OverLimit",
  otpExpired: "Error_OtpExpired",
  requestExpired: "Error_RequestExpired",
  accountFreeze: "Error_AccountFreeze",
  unauthorized: "Error_Unauthorized",
  maintenance: "Error_Maintenance",
  actionFailure: "action_failed",
  existedRule: "alert_rule_existed",
};
